### ISSUE TITLE
Linked Google Doc is editable

### ISSUE THREAD

**Issue by eigenfoo** [huggingface/awesome-papers#5]
The linked Google Doc for [_Scaling Laws for Neural Language Models_](https://github.com/huggingface/awesome-papers#march-24-2020) is editable by me. It should be made view-only by the public.

https://docs.google.com/document/d/1Rye61octaEF6FPHN3E7Bn2s-W3AWgMi1hukxrbkBmgY/edit

**Comment by julien-c** [comment]
Thanks for reporting, I think I've changed it to commenting-only. cc @TevenLeScao

**Comment by eigenfoo** [comment]
Thanks for the quick response @julien-c! Fastest resolved issue I've ever filed 😄
